### ISSUE TITLE
Use a logger library

### ISSUE THREAD

**Issue by nicobao** [krypton-org/krypton-android#2]
Instead of using plain System.out.println/err, go for a proper logger.
Logging is indeed a functionality that shall be delegated to the user of your library.
Use [a logging facade](https://stackoverflow.com/a/9741118/11046178) like SLF4j or Apache Commons Logging.
I have more experience with SLF4j.

**Comment by jrebecchi** [comment]
System.out.println/err is only used in tests, I guess it is not needed.
