### ISSUE TITLE
Use a GraphQL Client library

### ISSUE THREAD

**Issue by nicobao** [krypton-org/krypton-android#3]
Instead of writing the graphql queries by hand (!!!), use the nice [apollo-android](https://github.com/apollographql/apollo-android) graphql client.
You can also opt for [nodes](https://github.com/americanexpress/nodes). Seems abandoned, apollo is the de-facto standard in JS already - I am guessing not many people use nodes.
See the [official GraphQL site](https://graphql.org/code/#java-android).

**Comment by jrebecchi** [comment]
Overkill for our need.
