### ISSUE TITLE
Make public class Data outer

### ISSUE THREAD

**Issue by nicobao** [krypton-org/krypton-android#4]
No need to have an inner class for Data inside KryptonClient. Put it on its own file.

**Comment by dylrachwal** [comment]
Thanks for this issue, indeed, I made Data an interface and i have done many class implementing Data for my queries in the package utils. What do you think about it ?

**Comment by nicobao** [comment]
That sounds more like idiomatic Java. Great job! Send a pull-request, I will review it and give you my (humble) opinion on the design :).
