### ISSUE TITLE
Remove IDE-related files

### ISSUE THREAD

**Issue by nicobao** [krypton-org/krypton-android#9]
.project file and .settings directory should not be in this repository.
Those are Eclipse-generated files. Different people use different IDEs. IDE-generated files shall not be shared in public repositories. Add those files to .gitignore.
Also, I recommend that you check out IntelliJ instead if you want to stick with a GUI mouse-based IDE, it's more modern and probably more used today. (Or go for Emacs/vim and friends if you want to go hardcore, but say good bye to your productivity for ~1 month or more! )

**Comment by jrebecchi** [comment]
Done.
